# Import Library

In [6]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,LSTM
from keras import optimizers
from numpy import genfromtxt
import numpy as np
from keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler
from sklearn.externals import joblib
from keras.models import load_model
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# read dataset and output

In [7]:
dataset = genfromtxt('dataset/dataset.csv',delimiter=',')
dataset1 = genfromtxt('dataset/dataset1.csv',delimiter=',')
dataset2 = genfromtxt('dataset/dataset2.csv',delimiter=',')
dataset3 = genfromtxt('dataset/dataset3.csv',delimiter=',')
dataset4 = genfromtxt('dataset/dataset4.csv',delimiter=',')
dataset5 = genfromtxt('dataset/dataset5.csv',delimiter=',')
dataset6 = genfromtxt('dataset/dataset6.csv',delimiter=',')
dataset7 = genfromtxt('dataset/dataset7.csv',delimiter=',')
dataset8 = genfromtxt('dataset/dataset8.csv',delimiter=',')
dataset9 = genfromtxt('dataset/dataset9.csv',delimiter=',')
dataset10 = genfromtxt('dataset/dataset10.csv',delimiter=',')
dataset11 = genfromtxt('dataset/dataset11.csv',delimiter=',')
dataset12 = genfromtxt('dataset/dataset12.csv',delimiter=',')
dataset13 = genfromtxt('dataset/dataset13.csv',delimiter=',')
dataset14 = genfromtxt('dataset/dataset14.csv',delimiter=',')
dataset15 = genfromtxt('dataset/dataset15.csv',delimiter=',')
dataset16 = genfromtxt('dataset/dataset16.csv',delimiter=',')
dataset17 = genfromtxt('dataset/dataset17.csv',delimiter=',')
dataset18 = genfromtxt('dataset/dataset18.csv',delimiter=',')
dataset19 = genfromtxt('dataset/dataset19.csv',delimiter=',')
dataset20 = genfromtxt('dataset/dataset20.csv',delimiter=',')
dataset21 = genfromtxt('dataset/dataset21.csv',delimiter=',')
dataset22 = genfromtxt('dataset/dataset22.csv',delimiter=',')
dataset23 = genfromtxt('dataset/dataset23.csv',delimiter=',')
dataset24 = genfromtxt('dataset/dataset24.csv',delimiter=',')
dataset25 = genfromtxt('dataset/dataset25.csv',delimiter=',')
dataset26 = genfromtxt('dataset/dataset26.csv',delimiter=',')
dataset27 = genfromtxt('dataset/dataset27.csv',delimiter=',')
dataset28 = genfromtxt('dataset/dataset28.csv',delimiter=',')
dataset29 = genfromtxt('dataset/dataset29.csv',delimiter=',')
dataset30 = genfromtxt('dataset/dataset30.csv',delimiter=',')
dataset31 = genfromtxt('dataset/dataset31.csv',delimiter=',')
dataset32 = genfromtxt('dataset/dataset32.csv',delimiter=',')
dataset33 = genfromtxt('dataset/dataset33.csv',delimiter=',')
dataset34 = genfromtxt('dataset/dataset34.csv',delimiter=',')
dataset35 = genfromtxt('dataset/dataset35.csv',delimiter=',')
dataset36 = genfromtxt('dataset/dataset36.csv',delimiter=',')
dataset37 = genfromtxt('dataset/dataset37.csv',delimiter=',')
dataset38 = genfromtxt('dataset/dataset38.csv',delimiter=',')
dataset39 = genfromtxt('dataset/dataset39.csv',delimiter=',')
dataset40 = genfromtxt('dataset/dataset40.csv',delimiter=',')
dataset41 = genfromtxt('dataset/dataset41.csv',delimiter=',')
dataset42 = genfromtxt('dataset/dataset42.csv',delimiter=',')
dataset43 = genfromtxt('dataset/dataset43.csv',delimiter=',')
dataset44 = genfromtxt('dataset/dataset44.csv',delimiter=',')
dataset45 = genfromtxt('dataset/dataset45.csv',delimiter=',')
dataset46 = genfromtxt('dataset/dataset46.csv',delimiter=',')
dataset47 = genfromtxt('dataset/dataset47.csv',delimiter=',')
dataset48 = genfromtxt('dataset/dataset48.csv',delimiter=',')

outputtrain = genfromtxt('dataset/outputtrain1hr.csv',delimiter=',')

# Normalization

In [8]:
datanorm = np.concatenate((dataset,dataset1,dataset2,dataset3,dataset4,dataset5,dataset6,dataset7,dataset8,dataset9,dataset10,
                                          dataset11,dataset12,dataset13,dataset14,dataset15,dataset16,dataset17,dataset18,dataset19,dataset20,
                                          dataset21,dataset22,dataset23,dataset24,dataset25,dataset26,dataset27,dataset28,dataset29,dataset30,
                                          dataset31,dataset32,dataset34,dataset35,dataset36,dataset37,dataset38,dataset39,dataset40,
                                          dataset41,dataset42,dataset43,dataset44,dataset45,dataset46,dataset47,dataset48,))
scaler = StandardScaler()
scaler.fit(datanorm)
dataset = scaler.transform(dataset)
dataset1 = scaler.transform(dataset1)
dataset2 = scaler.transform(dataset2)
dataset3 = scaler.transform(dataset3)
dataset4 = scaler.transform(dataset4)
dataset5 = scaler.transform(dataset5)
dataset6 = scaler.transform(dataset6)
dataset7 = scaler.transform(dataset7)
dataset8 = scaler.transform(dataset8)
dataset9 = scaler.transform(dataset9)
dataset10 = scaler.transform(dataset10)
dataset11 = scaler.transform(dataset11)
dataset12 = scaler.transform(dataset12)
dataset13 = scaler.transform(dataset13)
dataset14 = scaler.transform(dataset14)
dataset15 = scaler.transform(dataset15)
dataset16 = scaler.transform(dataset16)
dataset17 = scaler.transform(dataset17)
dataset18 = scaler.transform(dataset18)
dataset19 = scaler.transform(dataset19)
dataset20 = scaler.transform(dataset20)
dataset21 = scaler.transform(dataset21)
dataset22 = scaler.transform(dataset22)
dataset23 = scaler.transform(dataset23)
dataset24 = scaler.transform(dataset24)
dataset25 = scaler.transform(dataset25)
dataset26 = scaler.transform(dataset26)
dataset27 = scaler.transform(dataset27)
dataset28 = scaler.transform(dataset28)
dataset29 = scaler.transform(dataset29)
dataset30 = scaler.transform(dataset30)
dataset31 = scaler.transform(dataset31)
dataset32 = scaler.transform(dataset32)
dataset34 = scaler.transform(dataset34)
dataset35 = scaler.transform(dataset35)
dataset36 = scaler.transform(dataset36)
dataset37 = scaler.transform(dataset37)
dataset38 = scaler.transform(dataset38)
dataset39 = scaler.transform(dataset39)
dataset40 = scaler.transform(dataset40)
dataset41 = scaler.transform(dataset41)
dataset42 = scaler.transform(dataset42)
dataset43 = scaler.transform(dataset43)
dataset44 = scaler.transform(dataset44)
dataset45 = scaler.transform(dataset45)
dataset46 = scaler.transform(dataset46)
dataset47 = scaler.transform(dataset47)
dataset48 = scaler.transform(dataset48)

# save normalization model

In [10]:
joblib.dump(scaler, 'model_norm1hr.pkl')

['model_norm1hr.pkl']

# function split data

In [11]:
def getdataTimestep(dataset,hour):
    training = []
    start = 0
    end = 23
    for x in range(0,len(dataset)-end):
        training.append(dataset[(end-hour)+x:end+x,:])
    return training

# split data

In [12]:
hour = 23
x_train =  getdataTimestep(dataset,hour)+getdataTimestep(dataset1,hour)+getdataTimestep(dataset2,hour)+getdataTimestep(dataset3,hour)+getdataTimestep(dataset4,hour)+getdataTimestep(dataset5,hour)+getdataTimestep(dataset6,hour)+getdataTimestep(dataset7,hour)+getdataTimestep(dataset8,hour)+getdataTimestep(dataset9,hour)+getdataTimestep(dataset10,hour)+getdataTimestep(dataset11,hour)+getdataTimestep(dataset12,hour)+getdataTimestep(dataset13,hour)+getdataTimestep(dataset14,hour)+getdataTimestep(dataset15,hour)+getdataTimestep(dataset16,hour)+getdataTimestep(dataset17,hour)+getdataTimestep(dataset18,hour)+getdataTimestep(dataset19,hour)+getdataTimestep(dataset20,hour)+getdataTimestep(dataset21,hour)+getdataTimestep(dataset22,hour)+getdataTimestep(dataset23,hour)+getdataTimestep(dataset24,hour)+getdataTimestep(dataset25,hour)+getdataTimestep(dataset26,hour)+getdataTimestep(dataset27,hour)+getdataTimestep(dataset28,hour)+getdataTimestep(dataset29,hour)+getdataTimestep(dataset30,hour)+getdataTimestep(dataset31,hour)+getdataTimestep(dataset32,hour)+getdataTimestep(dataset34,hour)+getdataTimestep(dataset35,hour)+getdataTimestep(dataset36,hour)+getdataTimestep(dataset37,hour)+getdataTimestep(dataset38,hour)+getdataTimestep(dataset39,hour)+getdataTimestep(dataset40,hour)+getdataTimestep(dataset41,hour)+getdataTimestep(dataset42,hour)+getdataTimestep(dataset43,hour)+getdataTimestep(dataset44,hour)+getdataTimestep(dataset45,hour)+getdataTimestep(dataset46,hour)+getdataTimestep(dataset47,hour)+getdataTimestep(dataset48,hour)
x_train = np.array(x_train)
y_train = to_categorical(outputtrain)
print(len(x_train))
print(len(outputtrain))

33033
33033


# LSTM architecture

In [13]:
data_dim = 6
timesteps = 23

model = Sequential()
model.add(LSTM(32,input_shape=(timesteps,data_dim),return_sequences=True))#True = many to many
model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32))
model.add(Dropout(0.3))
model.add(Dense(6,activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Fit Model 

In [14]:
model.summary()
model.fit(x_train,y_train,epochs=100,batch_size=256);
scores = model.evaluate(x_train, y_train)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 23, 32)            4992      
_________________________________________________________________
lstm_2 (LSTM)                (None, 23, 32)            8320      
_________________________________________________________________
lstm_3 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dropout_1 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 198       
Total params: 21,830
Trainable params: 21,830
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
33033/33033 [==============================] - 8s 242us/step - loss: 0.7994 - acc: 0.6988
Epoch 2/100
33033/33033 [===========

33033/33033 [==============================] - 9s 288us/step - loss: 0.0748 - acc: 0.9706
Epoch 70/100
33033/33033 [==============================] - 10s 290us/step - loss: 0.0720 - acc: 0.9726
Epoch 71/100
33033/33033 [==============================] - 9s 281us/step - loss: 0.0721 - acc: 0.9707
Epoch 72/100
33033/33033 [==============================] - 9s 287us/step - loss: 0.0731 - acc: 0.9706
Epoch 73/100
33033/33033 [==============================] - 11s 332us/step - loss: 0.0728 - acc: 0.97230s - loss: 0.0733 - acc: 0.
Epoch 74/100
33033/33033 [==============================] - 10s 295us/step - loss: 0.0711 - acc: 0.9721
Epoch 75/100
33033/33033 [==============================] - 10s 298us/step - loss: 0.0702 - acc: 0.9727
Epoch 76/100
33033/33033 [==============================] - 10s 297us/step - loss: 0.0725 - acc: 0.9714
Epoch 77/100
33033/33033 [==============================] - 10s 300us/step - loss: 0.0691 - acc: 0.9731
Epoch 78/100
33033/33033 [===========================

# save model

In [15]:
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
model.save('my.modelLSTM1.h5')


acc: 97.41%


# Measure Performance 

# Load model LSTM and model normalization

In [16]:
model1 = load_model('my.modelLSTM1.h5')
scaler = joblib.load('model_norm1hr.pkl')

# read data test and output test

In [17]:
outputtest1 = genfromtxt('dataset/outputYtest1.csv',delimiter=',')
outputtest2 = genfromtxt('dataset/outputYtest2.csv',delimiter=',')
datatest1 = genfromtxt('dataset/datatest1.csv',delimiter=',')
datatest2 = genfromtxt('dataset/datatest2.csv',delimiter=',')

# normalization data test

In [18]:
datatest1 = scaler.transform(datatest1)
datatest2 = scaler.transform(datatest2)

# function measure performance model

In [19]:
def prediction(datatest,output):
    datax=[]
    for x in range(0,len(datatest)-23):
        datax.append(datatest[0+x:23+x,:])
    predict=[]
    for x in range(len(datax)):
        test1=[]
        test=[]
        test1.append(datax[x])
        test.append(test1)
        predict.append(model1.predict_classes(test))
    print("Accuracy = ",accuracy_score(predict,output))
    print("confusion matrix")
    print(confusion_matrix(output, predict, labels=[1, 2, 3,4,5]))

# predicted datatest

In [22]:
prediction(datatest1,outputtest1)
prediction(datatest2,outputtest2)

Accuracy =  0.924812030075188
confusion matrix
[[111   8   0   0   0]
 [ 13 435   0   0   0]
 [  0  24  48   0   0]
 [  0   0   0  21   5]
 [  0   0   0   0   0]]
Accuracy =  0.9743918053777209
confusion matrix
[[678  15   0   0   0]
 [  2  83   0   0   0]
 [  0   3   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]
