# Import Library

In [11]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,LSTM
from keras import optimizers
from numpy import genfromtxt
import numpy as np
from keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler
from sklearn.externals import joblib
from keras.models import load_model
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# read dataset and output

In [3]:
dataset = genfromtxt('dataset/dataset.csv',delimiter=',')
dataset1 = genfromtxt('dataset/dataset1.csv',delimiter=',')
dataset2 = genfromtxt('dataset/dataset2.csv',delimiter=',')
dataset3 = genfromtxt('dataset/dataset3.csv',delimiter=',')
dataset4 = genfromtxt('dataset/dataset4.csv',delimiter=',')
dataset5 = genfromtxt('dataset/dataset5.csv',delimiter=',')
dataset6 = genfromtxt('dataset/dataset6.csv',delimiter=',')
dataset7 = genfromtxt('dataset/dataset7.csv',delimiter=',')
dataset8 = genfromtxt('dataset/dataset8.csv',delimiter=',')
dataset9 = genfromtxt('dataset/dataset9.csv',delimiter=',')
dataset10 = genfromtxt('dataset/dataset10.csv',delimiter=',')
dataset11 = genfromtxt('dataset/dataset11.csv',delimiter=',')
dataset12 = genfromtxt('dataset/dataset12.csv',delimiter=',')
dataset13 = genfromtxt('dataset/dataset13.csv',delimiter=',')
dataset14 = genfromtxt('dataset/dataset14.csv',delimiter=',')
dataset15 = genfromtxt('dataset/dataset15.csv',delimiter=',')
dataset16 = genfromtxt('dataset/dataset16.csv',delimiter=',')
dataset17 = genfromtxt('dataset/dataset17.csv',delimiter=',')
dataset18 = genfromtxt('dataset/dataset18.csv',delimiter=',')
dataset19 = genfromtxt('dataset/dataset19.csv',delimiter=',')
dataset20 = genfromtxt('dataset/dataset20.csv',delimiter=',')
dataset21 = genfromtxt('dataset/dataset21.csv',delimiter=',')
dataset22 = genfromtxt('dataset/dataset22.csv',delimiter=',')
dataset23 = genfromtxt('dataset/dataset23.csv',delimiter=',')
dataset24 = genfromtxt('dataset/dataset24.csv',delimiter=',')
dataset25 = genfromtxt('dataset/dataset25.csv',delimiter=',')
dataset26 = genfromtxt('dataset/dataset26.csv',delimiter=',')
dataset27 = genfromtxt('dataset/dataset27.csv',delimiter=',')
dataset28 = genfromtxt('dataset/dataset28.csv',delimiter=',')
dataset29 = genfromtxt('dataset/dataset29.csv',delimiter=',')
dataset30 = genfromtxt('dataset/dataset30.csv',delimiter=',')
dataset31 = genfromtxt('dataset/dataset31.csv',delimiter=',')
dataset32 = genfromtxt('dataset/dataset32.csv',delimiter=',')
dataset33 = genfromtxt('dataset/dataset33.csv',delimiter=',')
dataset34 = genfromtxt('dataset/dataset34.csv',delimiter=',')
dataset35 = genfromtxt('dataset/dataset35.csv',delimiter=',')
dataset36 = genfromtxt('dataset/dataset36.csv',delimiter=',')
dataset37 = genfromtxt('dataset/dataset37.csv',delimiter=',')
dataset38 = genfromtxt('dataset/dataset38.csv',delimiter=',')
dataset39 = genfromtxt('dataset/dataset39.csv',delimiter=',')
dataset40 = genfromtxt('dataset/dataset40.csv',delimiter=',')
dataset41 = genfromtxt('dataset/dataset41.csv',delimiter=',')
dataset42 = genfromtxt('dataset/dataset42.csv',delimiter=',')
dataset43 = genfromtxt('dataset/dataset43.csv',delimiter=',')
dataset44 = genfromtxt('dataset/dataset44.csv',delimiter=',')
dataset45 = genfromtxt('dataset/dataset45.csv',delimiter=',')
dataset46 = genfromtxt('dataset/dataset46.csv',delimiter=',')
dataset47 = genfromtxt('dataset/dataset47.csv',delimiter=',')
dataset48 = genfromtxt('dataset/dataset48.csv',delimiter=',')
dataset49 = genfromtxt('dataset/dataset49.csv',delimiter=',')
dataset50 = genfromtxt('dataset/dataset50.csv',delimiter=',')
dataset51 = genfromtxt('dataset/dataset51.csv',delimiter=',')
dataset52 = genfromtxt('dataset/dataset52.csv',delimiter=',')
dataset53 = genfromtxt('dataset/dataset53.csv',delimiter=',')
dataset54 = genfromtxt('dataset/dataset54.csv',delimiter=',')
dataset55 = genfromtxt('dataset/dataset55.csv',delimiter=',')
dataset56 = genfromtxt('dataset/dataset56.csv',delimiter=',')
dataset57 = genfromtxt('dataset/dataset57.csv',delimiter=',')
dataset58 = genfromtxt('dataset/dataset58.csv',delimiter=',')
dataset59 = genfromtxt('dataset/dataset59.csv',delimiter=',')
dataset60 = genfromtxt('dataset/dataset60.csv',delimiter=',')
dataset61 = genfromtxt('dataset/dataset61.csv',delimiter=',')
dataset62 = genfromtxt('dataset/dataset62.csv',delimiter=',')
dataset63 = genfromtxt('dataset/dataset63.csv',delimiter=',')
dataset64 = genfromtxt('dataset/dataset64.csv',delimiter=',')
dataset65 = genfromtxt('dataset/dataset65.csv',delimiter=',')
dataset66 = genfromtxt('dataset/dataset66.csv',delimiter=',')
dataset67 = genfromtxt('dataset/dataset67.csv',delimiter=',')
dataset68 = genfromtxt('dataset/dataset68.csv',delimiter=',')
dataset69 = genfromtxt('dataset/dataset69.csv',delimiter=',')
dataset70 = genfromtxt('dataset/dataset70.csv',delimiter=',')
dataset71 = genfromtxt('dataset/dataset71.csv',delimiter=',')
dataset72 = genfromtxt('dataset/dataset72.csv',delimiter=',')
dataset73 = genfromtxt('dataset/dataset73.csv',delimiter=',')
dataset74 = genfromtxt('dataset/dataset74.csv',delimiter=',')
dataset75 = genfromtxt('dataset/dataset75.csv',delimiter=',')
dataset76 = genfromtxt('dataset/dataset76.csv',delimiter=',')
dataset77 = genfromtxt('dataset/dataset77.csv',delimiter=',')
dataset78 = genfromtxt('dataset/dataset78.csv',delimiter=',')
dataset79 = genfromtxt('dataset/dataset79.csv',delimiter=',')
dataset80 = genfromtxt('dataset/dataset80.csv',delimiter=',')
dataset81 = genfromtxt('dataset/dataset81.csv',delimiter=',')
dataset82 = genfromtxt('dataset/dataset82.csv',delimiter=',')
dataset83 = genfromtxt('dataset/dataset83.csv',delimiter=',')
dataset84 = genfromtxt('dataset/dataset84.csv',delimiter=',')
dataset85 = genfromtxt('dataset/dataset85.csv',delimiter=',')
dataset86 = genfromtxt('dataset/dataset86.csv',delimiter=',')
dataset87 = genfromtxt('dataset/dataset87.csv',delimiter=',')
dataset88 = genfromtxt('dataset/dataset88.csv',delimiter=',')
dataset89 = genfromtxt('dataset/dataset89.csv',delimiter=',')
dataset90 = genfromtxt('dataset/dataset90.csv',delimiter=',')
dataset91 = genfromtxt('dataset/dataset91.csv',delimiter=',')
dataset92 = genfromtxt('dataset/dataset92.csv',delimiter=',')
dataset93 = genfromtxt('dataset/dataset93.csv',delimiter=',')
dataset94 = genfromtxt('dataset/dataset94.csv',delimiter=',')
dataset95 = genfromtxt('dataset/dataset95.csv',delimiter=',')

outputtrain = genfromtxt('dataset/outputtrain24hr.csv',delimiter=',')

# Normalization

In [4]:
datanorm = np.concatenate((dataset,dataset1,dataset2,dataset3,dataset4,dataset5,dataset6,dataset7,dataset8,dataset9,dataset10,
                                          dataset11,dataset12,dataset13,dataset14,dataset15,dataset16,dataset17,dataset18,dataset19,dataset20,
                                          dataset21,dataset22,dataset23,dataset24,dataset25,dataset26,dataset27,dataset28,dataset29,dataset30,dataset31,dataset32,
                                           dataset33,dataset34,dataset35,dataset36,dataset37,dataset38,dataset39,dataset40,
                                          dataset41,dataset42,dataset43,dataset44,dataset45,dataset46,dataset47,dataset48,dataset49,dataset50,
                                          dataset51,dataset52,dataset53,dataset54,dataset55,dataset56,dataset57,dataset58,dataset59,dataset60,
                                          dataset61,dataset62,dataset63,dataset64,dataset65,dataset66,dataset67,dataset68,dataset69,dataset70,
                                          dataset71,dataset72,dataset73,dataset74,dataset75,dataset76,dataset77,dataset78,dataset79,dataset80,
                                          dataset81,dataset82,dataset83,dataset84,dataset85,dataset86,dataset87,dataset88,dataset89,dataset90,
                                          dataset91,dataset92,dataset93,dataset94,dataset95))
scaler = StandardScaler()
scaler.fit(datanorm)
dataset = scaler.transform(dataset)
dataset1 = scaler.transform(dataset1)
dataset2 = scaler.transform(dataset2)
dataset3 = scaler.transform(dataset3)
dataset4 = scaler.transform(dataset4)
dataset5 = scaler.transform(dataset5)
dataset6 = scaler.transform(dataset6)
dataset7 = scaler.transform(dataset7)
dataset8 = scaler.transform(dataset8)
dataset9 = scaler.transform(dataset9)
dataset10 = scaler.transform(dataset10)
dataset11 = scaler.transform(dataset11)
dataset12 = scaler.transform(dataset12)
dataset13 = scaler.transform(dataset13)
dataset14 = scaler.transform(dataset14)
dataset15 = scaler.transform(dataset15)
dataset16 = scaler.transform(dataset16)
dataset17 = scaler.transform(dataset17)
dataset18 = scaler.transform(dataset18)
dataset19 = scaler.transform(dataset19)
dataset20 = scaler.transform(dataset20)
dataset21 = scaler.transform(dataset21)
dataset22 = scaler.transform(dataset22)
dataset23 = scaler.transform(dataset23)
dataset24 = scaler.transform(dataset24)
dataset25 = scaler.transform(dataset25)
dataset26 = scaler.transform(dataset26)
dataset27 = scaler.transform(dataset27)
dataset28 = scaler.transform(dataset28)
dataset29 = scaler.transform(dataset29)
dataset30 = scaler.transform(dataset30)
dataset31 = scaler.transform(dataset31)
dataset32 = scaler.transform(dataset32)
dataset33 = scaler.transform(dataset33)
dataset34 = scaler.transform(dataset34)
dataset35 = scaler.transform(dataset35)
dataset36 = scaler.transform(dataset36)
dataset37 = scaler.transform(dataset37)
dataset38 = scaler.transform(dataset38)
dataset39 = scaler.transform(dataset39)
dataset40 = scaler.transform(dataset40)
dataset41 = scaler.transform(dataset41)
dataset42 = scaler.transform(dataset42)
dataset43 = scaler.transform(dataset43)
dataset44 = scaler.transform(dataset44)
dataset45 = scaler.transform(dataset45)
dataset46 = scaler.transform(dataset46)
dataset47 = scaler.transform(dataset47)
dataset48 = scaler.transform(dataset48)
dataset49 = scaler.transform(dataset49)
dataset50 = scaler.transform(dataset50)
dataset51 = scaler.transform(dataset51)
dataset52 = scaler.transform(dataset52)
dataset53 = scaler.transform(dataset53)
dataset54 = scaler.transform(dataset54)
dataset55 = scaler.transform(dataset55)
dataset56 = scaler.transform(dataset56)
dataset57 = scaler.transform(dataset57)
dataset58 = scaler.transform(dataset58)
dataset59 = scaler.transform(dataset59)
dataset60 = scaler.transform(dataset60)
dataset61 = scaler.transform(dataset61)
dataset62 = scaler.transform(dataset62)
dataset63 = scaler.transform(dataset63)
dataset64 = scaler.transform(dataset64)
dataset65 = scaler.transform(dataset65)
dataset66 = scaler.transform(dataset66)
dataset67 = scaler.transform(dataset67)
dataset68 = scaler.transform(dataset68)
dataset69 = scaler.transform(dataset69)
dataset70 = scaler.transform(dataset70)
dataset71 = scaler.transform(dataset71)
dataset72 = scaler.transform(dataset72)
dataset73 = scaler.transform(dataset73)
dataset74 = scaler.transform(dataset74)
dataset75 = scaler.transform(dataset75)
dataset76 = scaler.transform(dataset76)
dataset77 = scaler.transform(dataset77)
dataset78 = scaler.transform(dataset78)
dataset79 = scaler.transform(dataset79)
dataset80 = scaler.transform(dataset80)
dataset81 = scaler.transform(dataset81)
dataset82 = scaler.transform(dataset82)
dataset83 = scaler.transform(dataset83)
dataset84 = scaler.transform(dataset84)
dataset85 = scaler.transform(dataset85)
dataset86 = scaler.transform(dataset86)
dataset87 = scaler.transform(dataset87)
dataset88 = scaler.transform(dataset88)
dataset89 = scaler.transform(dataset89)
dataset90 = scaler.transform(dataset90)
dataset91 = scaler.transform(dataset91)
dataset92 = scaler.transform(dataset92)
dataset93 = scaler.transform(dataset93)
dataset94 = scaler.transform(dataset94)
dataset95 = scaler.transform(dataset95)

# save normalization model

In [12]:
joblib.dump(scaler, 'model_norm24hr.pkl')

['model_norm24hr.pkl']

# function split data

In [7]:
def getdataTimestep(dataset,hour):
    training = []
    hoursp=hour
    start = 0
    end = 24
    data1 = dataset[0:len(dataset)-23,:]
    for x in range(0,len(data1)-end):
        training.append(data1[(end-hoursp)+x:end+x,:])
    return training

# split data

In [8]:
hour = 24
x_train =  getdataTimestep(dataset,hour)+getdataTimestep(dataset1,hour)+getdataTimestep(dataset2,hour)+getdataTimestep(dataset3,hour)+getdataTimestep(dataset4,hour)+getdataTimestep(dataset5,hour)+getdataTimestep(dataset6,hour)+getdataTimestep(dataset7,hour)+getdataTimestep(dataset8,hour)+getdataTimestep(dataset9,hour)+getdataTimestep(dataset10,hour)+getdataTimestep(dataset11,hour)+getdataTimestep(dataset12,hour)+getdataTimestep(dataset13,hour)+getdataTimestep(dataset14,hour)+getdataTimestep(dataset15,hour)+getdataTimestep(dataset16,hour)+getdataTimestep(dataset17,hour)+getdataTimestep(dataset18,hour)+getdataTimestep(dataset19,hour)+getdataTimestep(dataset20,hour)+getdataTimestep(dataset21,hour)+getdataTimestep(dataset22,hour)+getdataTimestep(dataset23,hour)+getdataTimestep(dataset24,hour)+getdataTimestep(dataset25,hour)+getdataTimestep(dataset26,hour)+getdataTimestep(dataset27,hour)+getdataTimestep(dataset28,hour)+getdataTimestep(dataset29,hour)+getdataTimestep(dataset30,hour)+getdataTimestep(dataset31,hour)+getdataTimestep(dataset32,hour)+getdataTimestep(dataset33,hour)+getdataTimestep(dataset34,hour)+getdataTimestep(dataset35,hour)+getdataTimestep(dataset36,hour)+getdataTimestep(dataset37,hour)+getdataTimestep(dataset38,hour)+getdataTimestep(dataset39,hour)+getdataTimestep(dataset40,hour)+getdataTimestep(dataset41,hour)+getdataTimestep(dataset42,hour)+getdataTimestep(dataset43,hour)+getdataTimestep(dataset44,hour)+getdataTimestep(dataset45,hour)+getdataTimestep(dataset46,hour)+getdataTimestep(dataset47,hour)+getdataTimestep(dataset48,hour)+getdataTimestep(dataset49,hour)+getdataTimestep(dataset50,hour)+getdataTimestep(dataset51,hour)+getdataTimestep(dataset52,hour)+getdataTimestep(dataset53,hour)+getdataTimestep(dataset54,hour)+getdataTimestep(dataset55,hour)+getdataTimestep(dataset56,hour)+getdataTimestep(dataset57,hour)+getdataTimestep(dataset58,hour)+getdataTimestep(dataset59,hour)+getdataTimestep(dataset60,hour)+getdataTimestep(dataset61,hour)+getdataTimestep(dataset62,hour)+getdataTimestep(dataset63,hour)+getdataTimestep(dataset64,hour)+getdataTimestep(dataset65,hour)+getdataTimestep(dataset66,hour)+getdataTimestep(dataset67,hour)+getdataTimestep(dataset68,hour)+getdataTimestep(dataset69,hour)+getdataTimestep(dataset70,hour)+getdataTimestep(dataset71,hour)+getdataTimestep(dataset72,hour)+getdataTimestep(dataset73,hour)+getdataTimestep(dataset74,hour)+getdataTimestep(dataset75,hour)+getdataTimestep(dataset76,hour)+getdataTimestep(dataset77,hour)+getdataTimestep(dataset78,hour)+getdataTimestep(dataset79,hour)+getdataTimestep(dataset80,hour)+getdataTimestep(dataset81,hour)+getdataTimestep(dataset82,hour)+getdataTimestep(dataset83,hour)+getdataTimestep(dataset84,hour)+getdataTimestep(dataset85,hour)+getdataTimestep(dataset86,hour)+getdataTimestep(dataset87,hour)+getdataTimestep(dataset88,hour)+getdataTimestep(dataset89,hour)+getdataTimestep(dataset90,hour)+getdataTimestep(dataset91,hour)+getdataTimestep(dataset92,hour)+getdataTimestep(dataset93,hour)+getdataTimestep(dataset94,hour)+getdataTimestep(dataset95,hour)
x_train = np.array(x_train,np.float64)
outputtrain = np.array(outputtrain,np.float64)
y_train = to_categorical(outputtrain)
print(len(x_train))
print(len(outputtrain))
print(y_train)

69992
69992
[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


# LSTM architecture

In [9]:
data_dim = 6
timesteps = 24

model = Sequential()
model.add(LSTM(32,input_shape=(timesteps,data_dim),return_sequences=True))#True = many to many
model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32))
model.add(Dropout(0.3))
model.add(Dense(6,activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Fit Model

In [10]:
model.summary()
model.fit(x_train,y_train,epochs=100,batch_size=256);
scores = model.evaluate(x_train, y_train)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 24, 32)            4992      
_________________________________________________________________
lstm_2 (LSTM)                (None, 24, 32)            8320      
_________________________________________________________________
lstm_3 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dropout_1 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 198       
Total params: 21,830
Trainable params: 21,830
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
69992/69992 [==============================] - 17s 237us/step - loss: 1.0469 - acc: 0.5578
Epoch 2/100
69992/69992 [==========

69992/69992 [==============================] - 14s 203us/step - loss: 0.2539 - acc: 0.9084
Epoch 70/100
69992/69992 [==============================] - 15s 218us/step - loss: 0.2485 - acc: 0.9097
Epoch 71/100
69992/69992 [==============================] - 15s 213us/step - loss: 0.2447 - acc: 0.9110
Epoch 72/100
69992/69992 [==============================] - 15s 213us/step - loss: 0.2427 - acc: 0.9122
Epoch 73/100
69992/69992 [==============================] - 13s 191us/step - loss: 0.2379 - acc: 0.9126
Epoch 74/100
69992/69992 [==============================] - 14s 206us/step - loss: 0.2374 - acc: 0.9147
Epoch 75/100
69992/69992 [==============================] - 15s 213us/step - loss: 0.2357 - acc: 0.9145
Epoch 76/100
69992/69992 [==============================] - 16s 232us/step - loss: 0.2294 - acc: 0.9166
Epoch 77/100
69992/69992 [==============================] - 14s 202us/step - loss: 0.2280 - acc: 0.9176
Epoch 78/100
69992/69992 [==============================] - 13s 189us/step - 

# save model

In [13]:
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
model.save('my.modelLSTM24hr.h5')


acc: 93.11%


# Measure Performance

# Load model LSTM and model normalization

In [14]:
scaler = joblib.load('model_norm24hr.pkl')
model24 = load_model('my.modelLSTM24hr.h5')

# read data test and output test

In [15]:
outputtest1 = genfromtxt('dataset/outputYtest1.csv',delimiter=',')
outputtest2 = genfromtxt('dataset/outputYtest2.csv',delimiter=',')
datatest1 = genfromtxt('dataset/datatest1.csv',delimiter=',')
datatest2 = genfromtxt('dataset/datatest2.csv',delimiter=',')

# normalization data test

In [16]:
datatest1 = scaler.transform(datatest1)
datatest2 = scaler.transform(datatest2)

# function measure performance model

In [17]:
def prediction(datatest,output):
    newoutput=[]
    datax=[]
    data1 = datatest[0:len(datatest)-23,:]
    for x in range(len(output)-24):
        newoutput.append(output[24+x])
    for x in range(len(data1)-24):
        datax.append(data1[0+x:24+x,:])
    predict=[]
    for x in range(len(datax)):
        test24=[]
        test=[]
        test24.append(datax[x])
        test.append(test24)
        predict.append(model24.predict_classes(test))
    print(accuracy_score(predict,newoutput))
    print(confusion_matrix(newoutput, predict, labels=[1, 2, 3,4,5]))

# predicted datatest

In [18]:
prediction(datatest1,outputtest1)
prediction(datatest2,outputtest2)

0.9609984399375975
[[118   1   0   0   0]
 [ 19 425   4   0   0]
 [  0   1  58   0   0]
 [  0   0   0  15   0]
 [  0   0   0   0   0]]
0.809775429326288
[[571  87  16   0   0]
 [ 37  42   1   0   0]
 [  3   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]
